/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeAreasIndexRouteImport } from './routes/practice-areas.index'
import { Route as PracticeAreasSlugRouteImport } from './routes/practice-areas.$slug'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasIndexRoute = PracticeAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeAreasRoute,
} as any)
const PracticeAreasSlugRoute = PracticeAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PracticeAreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/practice-areas': typeof PracticeAreasRouteWithChildren
  '/results': typeof ResultsRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/results': typeof ResultsRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/practice-areas': typeof PracticeAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/practice-areas': typeof PracticeAreasRouteWithChildren
  '/results': typeof ResultsRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/practice-areas'
    | '/results'
    | '/practice-areas/$slug'
    | '/practice-areas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/results' | '/practice-areas/$slug' | '/practice-areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/practice-areas'
    | '/results'
    | '/practice-areas/$slug'
    | '/practice-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PracticeAreasRoute: typeof PracticeAreasRouteWithChildren
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/': {
      id: '/practice-areas/'
      path: '/'
      fullPath: '/practice-areas/'
      preLoaderRoute: typeof PracticeAreasIndexRouteImport
      parentRoute: typeof PracticeAreasRoute
    }
    '/practice-areas/$slug': {
      id: '/practice-areas/$slug'
      path: '/$slug'
      fullPath: '/practice-areas/$slug'
      preLoaderRoute: typeof PracticeAreasSlugRouteImport
      parentRoute: typeof PracticeAreasRoute
    }
  }
}

interface PracticeAreasRouteChildren {
  PracticeAreasSlugRoute: typeof PracticeAreasSlugRoute
  PracticeAreasIndexRoute: typeof PracticeAreasIndexRoute
}

const PracticeAreasRouteChildren: PracticeAreasRouteChildren = {
  PracticeAreasSlugRoute: PracticeAreasSlugRoute,
  PracticeAreasIndexRoute: PracticeAreasIndexRoute,
}

const PracticeAreasRouteWithChildren = PracticeAreasRoute._addFileChildren(
  PracticeAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PracticeAreasRoute: PracticeAreasRouteWithChildren,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
